#!/bin/bash
#Install micro-ros-agent for Communication beetween ESP32 and Nvidia Jetson Nano Orin (Ubuntu 22.04)

# Create a workspace and download the micro-ROS tools
mkdir -p ~/ros2_ws/src
cd ~/ros2_ws/src
git clone -b humble https://github.com/micro-ROS/micro_ros_setup.git || echo "micro_ros_setup already cloned"

echo "Update dependencies using rosdep"
sudo apt update && rosdep update
rosdep install -i --from-path . --rosdistro humble -y

# Install pip
sudo apt-get install python3-pip

echo "Building workspace..."
colcon build --packages-select micro_ros_setup

# Bash for the same Terminal
source install/local_setup.bash

# Check Installation
ros2 pkg list

git clone -b humble https://github.com/micro-ROS/micro-ROS-Agent || echo "micro_ros_agent already cloned"
git clone -b humble https://github.com/micro-ROS/micro_ros_msgs.git || echo "micro_ros_msgs already cloned"

colcon build --packages-select micro_ros_msgs
colcon build --packages-select micro_ros_agent

# Bash for the same Terminal
source install/local_setup.bash

# Test run, USB- not found so find the right one!
ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyUSB0

# Unplug the device
ls /dev/tty* > before.txt

# Plug in the device
ls /dev/tty* > after.txt

# Compare with diff command
diff before.txt after.txt

pip install pyserial
python3 -m serial.tools.list_ports

dmesg | grep ch341



