#!/bin/bash
#Install micro-ros-agent for Communication beetween ESP32 and Nvidia Jetson Nano Orin (Ubuntu 22.04)

# Create a workspace and download the micro-ROS tools
mkdir -p ~/ros2_ws/src
cd ~/ros2_ws/src
git clone -b humble https://github.com/micro-ROS/micro_ros_setup.git || echo "micro_ros_setup already cloned"

echo "Update dependencies using rosdep"
sudo apt update && rosdep update
rosdep install -i --from-path . --rosdistro humble -y

# Install pip
sudo apt-get install python3-pip

echo "Building workspace..."
colcon build --packages-select micro_ros_setup

# Bash for the same Terminal
source install/local_setup.bash

# Check Installation
ros2 pkg list

git clone -b humble https://github.com/micro-ROS/micro-ROS-Agent || echo "micro_ros_agent already cloned"
git clone -b humble https://github.com/micro-ROS/micro_ros_msgs.git || echo "micro_ros_msgs already cloned"

colcon build --packages-select micro_ros_msgs
colcon build --packages-select micro_ros_agent

# Bash for the same Terminal
source install/local_setup.bash

####################################################################################
# Many popular devices, such as the ESP32 interface with USB through a CH341 interface. 
# The default configurationt of the Jetson Orin does not have this module installed.
# Here's a quick walkthrough of how to get it running. (Jetson Hacks)
######################################################################

git clone https://github.com/jetsonhacks/jetson-orin-kernel-builder.git
cd jetson-orin-kernel-builder/prebuilt/jetpack-6.2.1
tar -xvf usb_serial_ch341.tar.xz
cd usb_serial_ch341
ls -l install_module_ch341.sh

# make it executable and run it
chmod +x install_module_ch341.sh
sudo ./install_module_ch341.sh

# 2. Remove brltty it 
sudo apt remove --yes brltty
sudo udevadm control --reload-rules && sudo udevadm trigger
sudo reboot

######################################################################

# Test the USB Connecion to the 
ls /dev/ttyUSB*
# it should show up

# Add yourself to the dialout group
sudo usermod -aG dialout $USER
newgrp dialout   # or log out/in

# Test run, USB- not found so find the right one!
ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyUSB0

###### Now it should be running ############
#[1754717425.133137] info     | TermiosAgentLinux.cpp | init                     | running...             | fd: 3
#[1754717425.133816] info     | Root.cpp           | set_verbose_level        | logger setup           | verbose_level: 4


